workflows:
  ios-workflow:
    name: iOS Workflow
    working_directory: frontend

    environment:
      flutter: 3.29.2
      xcode: latest
      cocoapods: default

    scripts:
      - name: Flutter clean
        script: flutter clean

      - name: Get dependencies
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install

      - name: Build iOS Simulator
        script: |
          flutter build ios --debug --simulator --no-codesign

    artifacts:
      - build/ios/iphonesimulator/*.app
