workflows:
  ios-workflow:
    name: iOS Workflow
    working_directory: frontend

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Flutter clean
        script: flutter clean

      - name: Get dependencies
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS (no signing)
        script: flutter build ios --debug --simulator

    artifacts:
      - build/ios/iphonesimulator/*.app